######################################################################
# Automatically generated by qmake (2.01a) Sat Sep 22 14:31:42 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += appInfo.h bmpInfo.h spi_arduino.h window.h
SOURCES += application.c main.cpp window.cpp
