######################################################################
# Automatically generated by qmake (3.0) Fri Sep 21 17:49:01 2018
######################################################################
QT += widgets
TEMPLATE = app
TARGET = emtguiapp
INCLUDEPATH += .

# Input
HEADERS += appInfo.h bmpInfo.h spi_arduino.h window.h
SOURCES += application.c main.cpp window.cpp
