#!/bin/sh
#
# Start emtguiapp....
#

case "$1" in
  start)
        echo "Starting emt application..."
        #QWS_KEYBOARD=linuxinput:"" QWS_MOUSE_PROTO=linuxinput:"" /bin/emtguiapp -qws
        QWS_MOUSE_PROTO=tslib:"/dev/input/event0" /bin/emtguiapp -qws
        ;;
  stop)
        ;;
  restart|reload)
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
